---
title: "projet math"
author: "Matthias LAPU"
date: "2023-04-01"
output: html_document
---
test
Question 3 :
En utilisant les simulations de la partie précédente , estimer la probabilité que 
$$ P(S_n)>= 5)$$

Il est demandé de calculer, en notant W = #(trajectoires telles que S_n >= 5) :
$$
\frac{W}{M}
$$
On peut écrire W sous la forme  : 
$$
W_n = \sum_{k=1}^{n} 1_{(S_n>5)}
$$
Les X_k sont indépendants et donc les indicatrices sont égalements indépendants
Par indépendances des indicatrices on peut donc dire que
$$
W_n \approx B(n,p)
$$
Ainsi, avec k le nombre de réussites de plus que de défaites : 
$$
\sum_{k=50}^{100} P(X_k = 5+2k )
$$
$$
\sum_{i=50}^{100}\frac{100!}{i!(100-i)!}(\frac{1}{2})^{100-i}(\frac{1}{2})^i \approx 0.539795
$$

On ne traite que les cas de réussite (cas égal ou plus grand ). On veut plus de réussite que de défaite , les réussites sont +1 et les défaites -1 .
On calcule la moyenne empirique qui tend presque surement vers la moyenne. Il restera à estimer la variance empirique.
$$
\bar{X} = \frac{1}{n} \sum_{i=1}^n X_i
$$
On va centrer la moyenne et réduire par l'écart type pour avoir une gaussienne centrée réduite.
On note:

$$P(-u_\frac{\alpha}{2} \le \sqrt{n}*\frac{\bar{X_n}-\mu}{\sigma} \le u_\frac{\alpha}{2})$$
On développe :
$$
P(\bar{X_n}-u_\frac{\alpha}{2}\frac{\sigma}{\sqrt{n}} \le \mu \le \bar{X_n}+u_\frac{\alpha}{2}\frac{\sigma}{\sqrt{n}} )
$$
Ici on nous demande un intervalle de confiance de niveau 95% : 

$$
1 - \alpha = 0.95 \Rightarrow \alpha = 0.5
$$
D'après la table gaussienne on trouve que :
$$
u_\frac{\alpha}{2} = 1.960
$$
Il faut donc estimer la variance, on va l'estimer sans biais car nous savons d'après le cours que :
$$
\bar{V} = \frac{1}{n} \sum_{i=1}^{n} (X_i - \bar{X_n})
$$

est biaisé.

Ainsi :
$$
\bar{V} = \frac{1}{n-1} \sum_{i=1}^{n} (X_i - \bar{X_n})
\\
E[\bar{V}] = \sigma²
\\
\sigma = \sqrt{E[\bar{V}]}
$$

On importe donc les bonnes librairies : 

on va donc utiliser sum() et la librairie import statistics statistics.variance();
